export const START_STOP_PROTOCOL_HEADERS = {
  ANALYZE_USER_AI_AI_START: "[START][ANALYZE][USER-AI-AI]",
  ANALYZE_USER_AI_AI_STOP: "[STOP][ANALYZE][USER-AI-AI]",
  ANALYZE_AI_AI_START: "[START][ANALYZE][AI-AI]",
  ANALYZE_AI_AI_STOP: "[STOP][ANALYZE][AI-AI]",
  ANALYZE_AI_ASSISTANT_START: "[START][ANALYZE][AI-ASSISTANT]",
  ANALYZE_AI_ASSISTANT_STOP: "[STOP][ANALYZE][AI-ASSISTANT]",
} as const;
