import type {
  LabOperationCapabilityId,
  LabOperationSettingsMap,
  LabSettingsFieldMeta,
} from "./lab-capabilities.js";

export const LAB_OPERATION_SETTINGS_DEFAULTS: LabOperationSettingsMap = {
  "clip-export": {
    format: "mp4",
    quality: "balanced",
    fps: "source",
    includeAudio: true,
    applyRoiCrop: false,
    scale: "source",
  },
  "segment-stabilization": {
    shakiness: "medium",
    smoothing: 12,
    cropMode: "keep",
    quality: "balanced",
  },
  "frame-grab": {
    frameMode: "current",
    burstCount: 1,
    format: "png",
    quality: 92,
    timestampLabel: false,
  },
  "roi-crop": {
    padding: 0,
    aspectLock: "free",
    outputSize: "source",
    format: "png",
  },
  "enhanced-frame": {
    preset: "clarity",
    strength: 1,
    applyPreviewSettings: false,
    format: "png",
  },
  "before-after-variant": {
    layout: "side-by-side",
    revealPreset: "clarity",
    strength: 1,
    format: "png",
  },
  "image-comparison": {
    package: "detailed",
    layout: "side-by-side",
    metricSize: 512,
    splitPercent: 50,
    splitMode: "primary-left-reference-right",
    includeRoiDetail: true,
    format: "png",
    primaryZoom: 1,
    primaryScaleX: 1,
    primaryScaleY: 1,
    primaryOffsetX: 0,
    primaryOffsetY: 0,
    primaryRotation: 0,
    primaryAspectLock: true,
    referenceZoom: 1,
    referenceScaleX: 1,
    referenceScaleY: 1,
    referenceOffsetX: 0,
    referenceOffsetY: 0,
    referenceRotation: 0,
    referenceAspectLock: true,
    compositeMode: "none",
    centerGuide: true,
    marker1Enabled: false,
    marker1Side: "primary",
    marker1X: 50,
    marker1Y: 50,
    marker2Enabled: false,
    marker2Side: "primary",
    marker2X: 50,
    marker2Y: 50,
    marker3Enabled: false,
    marker3Side: "primary",
    marker3X: 50,
    marker3Y: 50,
  },
  "audio-extract": {
    format: "wav",
    channels: "stereo",
    sampleRate: 48000,
    timelineOnly: false,
  },
  "audio-cleanup": {
    denoise: "medium",
    highpassHz: 80,
    lowpassHz: 12000,
    normalizeTargetDb: -16,
    compressor: true,
  },
  "band-pass-voice": {
    lowHz: 120,
    highHz: 3800,
    widthQ: 1,
    gain: 1,
    channels: "mono",
  },
  "stem-separation": {
    model: "htdemucs",
    device: "cpu",
    stems: "all",
    segmentPreset: "balanced",
  },
};

export const LAB_OPERATION_SETTINGS_FIELDS: Record<
  LabOperationCapabilityId,
  LabSettingsFieldMeta[]
> = {
  "clip-export": [
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["mp4", "webm", "gif"].map((value) => ({ label: value.toUpperCase(), value })),
    },
    {
      id: "quality",
      label: "Quality",
      kind: "select",
      options: ["compact", "balanced", "high"].map((value) => ({ label: value, value })),
    },
    {
      id: "fps",
      label: "FPS",
      kind: "select",
      options: ["source", "12", "24", "30"].map((value) => ({ label: value, value })),
    },
    { id: "includeAudio", label: "Include audio", kind: "toggle" },
    { id: "applyRoiCrop", label: "Apply ROI crop", kind: "toggle" },
    {
      id: "scale",
      label: "Scale",
      kind: "select",
      options: ["source", "480p", "720p", "1080p"].map((value) => ({ label: value, value })),
    },
  ],
  "segment-stabilization": [
    {
      id: "shakiness",
      label: "Shakiness",
      kind: "select",
      options: ["low", "medium", "high"].map((value) => ({ label: value, value })),
    },
    { id: "smoothing", label: "Smoothing", kind: "number", min: 1, max: 30, step: 1 },
    {
      id: "cropMode",
      label: "Crop",
      kind: "select",
      options: ["keep", "adaptive", "fixed"].map((value) => ({ label: value, value })),
    },
    {
      id: "quality",
      label: "Quality",
      kind: "select",
      options: ["compact", "balanced", "high"].map((value) => ({ label: value, value })),
    },
  ],
  "frame-grab": [
    {
      id: "frameMode",
      label: "Frame",
      kind: "select",
      options: ["current", "middle", "burst"].map((value) => ({ label: value, value })),
    },
    { id: "burstCount", label: "Burst", kind: "number", min: 1, max: 12, step: 1 },
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["png", "jpg", "webp"].map((value) => ({ label: value.toUpperCase(), value })),
    },
    { id: "quality", label: "Quality", kind: "number", min: 1, max: 100, step: 1, unit: "%" },
    { id: "timestampLabel", label: "Timestamp label", kind: "toggle" },
  ],
  "roi-crop": [
    { id: "padding", label: "Padding", kind: "number", min: 0, max: 100, step: 1, unit: "px" },
    {
      id: "aspectLock",
      label: "Aspect",
      kind: "select",
      options: ["free", "square", "16:9", "4:3"].map((value) => ({ label: value, value })),
    },
    {
      id: "outputSize",
      label: "Size",
      kind: "select",
      options: ["source", "512", "1024", "2048"].map((value) => ({ label: value, value })),
    },
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["png", "jpg", "webp"].map((value) => ({ label: value.toUpperCase(), value })),
    },
  ],
  "enhanced-frame": [
    {
      id: "preset",
      label: "Preset",
      kind: "select",
      options: ["clarity", "low-light", "edge", "forensic"].map((value) => ({
        label: value,
        value,
      })),
    },
    { id: "strength", label: "Strength", kind: "number", min: 0.25, max: 2, step: 0.05 },
    { id: "applyPreviewSettings", label: "Apply preview", kind: "toggle" },
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["png", "jpg", "webp"].map((value) => ({ label: value.toUpperCase(), value })),
    },
  ],
  "before-after-variant": [
    {
      id: "layout",
      label: "Layout",
      kind: "select",
      options: ["side-by-side", "stacked", "wipe"].map((value) => ({ label: value, value })),
    },
    {
      id: "revealPreset",
      label: "Reveal",
      kind: "select",
      options: ["clarity", "low-light", "edge", "forensic"].map((value) => ({
        label: value,
        value,
      })),
    },
    { id: "strength", label: "Strength", kind: "number", min: 0.25, max: 2, step: 0.05 },
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["png", "jpg", "webp"].map((value) => ({ label: value.toUpperCase(), value })),
    },
  ],
  "image-comparison": [
    {
      id: "package",
      label: "Package",
      kind: "select",
      options: ["overview", "detailed"].map((value) => ({ label: value, value })),
    },
    {
      id: "layout",
      label: "Layout",
      kind: "select",
      options: ["side-by-side", "stacked"].map((value) => ({ label: value, value })),
    },
    {
      id: "metricSize",
      label: "Metric size",
      kind: "select",
      options: ["256", "512", "768"].map((value) => ({ label: `${value}px`, value })),
    },
    {
      id: "splitMode",
      label: "Split",
      kind: "select",
      options: ["primary-left-reference-right", "primary-mirror"].map((value) => ({
        label: value,
        value,
      })),
    },
    { id: "splitPercent", label: "Split %", kind: "number", min: 5, max: 95, step: 1 },
    { id: "includeRoiDetail", label: "ROI detail", kind: "toggle" },
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["png", "jpg", "webp"].map((value) => ({ label: value.toUpperCase(), value })),
    },
    {
      id: "primaryZoom",
      label: "A · Yakınlaştırma",
      kind: "number",
      min: 0.25,
      max: 4,
      step: 0.05,
    },
    { id: "primaryAspectLock", label: "A · En/boy oranını koru", kind: "toggle" },
    { id: "primaryScaleX", label: "A · X ölçeği", kind: "number", min: 0.25, max: 4, step: 0.05 },
    { id: "primaryScaleY", label: "A · Y ölçeği", kind: "number", min: 0.25, max: 4, step: 0.05 },
    {
      id: "primaryOffsetX",
      label: "A · Yatay konum",
      kind: "number",
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    {
      id: "primaryOffsetY",
      label: "A · Dikey konum",
      kind: "number",
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    {
      id: "primaryRotation",
      label: "A · Döndür",
      kind: "number",
      min: -180,
      max: 180,
      step: 0.5,
      unit: "°",
    },
    {
      id: "referenceZoom",
      label: "B · Yakınlaştırma",
      kind: "number",
      min: 0.25,
      max: 4,
      step: 0.05,
    },
    { id: "referenceAspectLock", label: "B · En/boy oranını koru", kind: "toggle" },
    { id: "referenceScaleX", label: "B · X ölçeği", kind: "number", min: 0.25, max: 4, step: 0.05 },
    { id: "referenceScaleY", label: "B · Y ölçeği", kind: "number", min: 0.25, max: 4, step: 0.05 },
    {
      id: "referenceOffsetX",
      label: "B · Yatay konum",
      kind: "number",
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    {
      id: "referenceOffsetY",
      label: "B · Dikey konum",
      kind: "number",
      min: -100,
      max: 100,
      step: 1,
      unit: "%",
    },
    {
      id: "referenceRotation",
      label: "B · Döndür",
      kind: "number",
      min: -180,
      max: 180,
      step: 0.5,
      unit: "°",
    },
    {
      id: "compositeMode",
      label: "Yarım yüz birleştirme",
      kind: "select",
      options: [
        { label: "Kapalı", value: "none" },
        { label: "A sol · B sağ", value: "primary-left-reference-right" },
        { label: "B sol · A sağ", value: "reference-left-primary-right" },
      ],
    },
    { id: "centerGuide", label: "Merkez çizgisini göster", kind: "toggle" },
    { id: "marker1Enabled", label: "İşaret 1", kind: "toggle" },
    {
      id: "marker1Side",
      label: "İşaret 1 tarafı",
      kind: "select",
      options: [
        { label: "A", value: "primary" },
        { label: "B", value: "reference" },
      ],
    },
    {
      id: "marker1X",
      label: "İşaret 1 · X",
      kind: "number",
      min: 0,
      max: 100,
      step: 0.5,
      unit: "%",
    },
    {
      id: "marker1Y",
      label: "İşaret 1 · Y",
      kind: "number",
      min: 0,
      max: 100,
      step: 0.5,
      unit: "%",
    },
    { id: "marker2Enabled", label: "İşaret 2", kind: "toggle" },
    {
      id: "marker2Side",
      label: "İşaret 2 tarafı",
      kind: "select",
      options: [
        { label: "A", value: "primary" },
        { label: "B", value: "reference" },
      ],
    },
    {
      id: "marker2X",
      label: "İşaret 2 · X",
      kind: "number",
      min: 0,
      max: 100,
      step: 0.5,
      unit: "%",
    },
    {
      id: "marker2Y",
      label: "İşaret 2 · Y",
      kind: "number",
      min: 0,
      max: 100,
      step: 0.5,
      unit: "%",
    },
    { id: "marker3Enabled", label: "İşaret 3", kind: "toggle" },
    {
      id: "marker3Side",
      label: "İşaret 3 tarafı",
      kind: "select",
      options: [
        { label: "A", value: "primary" },
        { label: "B", value: "reference" },
      ],
    },
    {
      id: "marker3X",
      label: "İşaret 3 · X",
      kind: "number",
      min: 0,
      max: 100,
      step: 0.5,
      unit: "%",
    },
    {
      id: "marker3Y",
      label: "İşaret 3 · Y",
      kind: "number",
      min: 0,
      max: 100,
      step: 0.5,
      unit: "%",
    },
  ],
  "audio-extract": [
    {
      id: "format",
      label: "Format",
      kind: "select",
      options: ["wav", "flac", "mp3"].map((value) => ({ label: value.toUpperCase(), value })),
    },
    {
      id: "channels",
      label: "Channels",
      kind: "select",
      options: ["mono", "stereo", "source"].map((value) => ({ label: value, value })),
    },
    {
      id: "sampleRate",
      label: "Sample rate",
      kind: "select",
      options: ["16000", "44100", "48000"].map((value) => ({ label: `${value} Hz`, value })),
    },
    { id: "timelineOnly", label: "Selection only", kind: "toggle" },
  ],
  "audio-cleanup": [
    {
      id: "denoise",
      label: "Denoise",
      kind: "select",
      options: ["light", "medium", "strong"].map((value) => ({ label: value, value })),
    },
    {
      id: "highpassHz",
      label: "High-pass",
      kind: "number",
      min: 20,
      max: 1000,
      step: 10,
      unit: "Hz",
    },
    {
      id: "lowpassHz",
      label: "Low-pass",
      kind: "number",
      min: 1000,
      max: 20000,
      step: 100,
      unit: "Hz",
    },
    {
      id: "normalizeTargetDb",
      label: "Normalize",
      kind: "number",
      min: -30,
      max: -6,
      step: 1,
      unit: "dB",
    },
    { id: "compressor", label: "Compressor", kind: "toggle" },
  ],
  "band-pass-voice": [
    { id: "lowHz", label: "Low", kind: "number", min: 20, max: 1000, step: 10, unit: "Hz" },
    { id: "highHz", label: "High", kind: "number", min: 1000, max: 10000, step: 100, unit: "Hz" },
    { id: "widthQ", label: "Q", kind: "number", min: 0.1, max: 10, step: 0.1 },
    { id: "gain", label: "Gain", kind: "number", min: 0.5, max: 8, step: 0.1, unit: "x" },
    {
      id: "channels",
      label: "Channels",
      kind: "select",
      options: ["mono", "stereo"].map((value) => ({ label: value, value })),
    },
  ],
  "stem-separation": [
    {
      id: "model",
      label: "Model",
      kind: "select",
      options: ["htdemucs", "htdemucs_ft", "mdx_extra"].map((value) => ({ label: value, value })),
    },
    {
      id: "device",
      label: "Device",
      kind: "select",
      options: ["cpu", "cuda"].map((value) => ({ label: value, value })),
    },
    {
      id: "stems",
      label: "Stems",
      kind: "select",
      options: ["all", "vocals", "drums", "bass", "other"].map((value) => ({
        label: value,
        value,
      })),
    },
    {
      id: "segmentPreset",
      label: "Segment",
      kind: "select",
      options: ["fast", "balanced", "quality"].map((value) => ({ label: value, value })),
    },
  ],
};
